apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged-disallowed
  namespace: default
  labels:
    app: nginx-privileged
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    securityContext:
      privileged: true
