apiVersion: v1
kind: Pod
metadata:
  name: nginx-proc-mount-disallowed
  namespace: default
  labels:
    app: nginx-proc-mount
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    securityContext:
      procMount: Unmasked #Default
