apiVersion: v1
kind: Pod
metadata:
  name: nginx-host-networking-ports-disallowed
  namespace: default
  labels:
    app: nginx-host-networking-ports
spec:
  hostNetwork: true
  ephemeralContainers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 9001
      hostPort: 9001
