apiVersion: v1
kind: Pod
metadata:
  name: nginx-privilege-escalation-disallowed
  namespace: nginx
  labels:
    app: nginx-privilege-escalation
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    securityContext:
      allowPrivilegeEscalation: true
