apiVersion: v1
kind: Pod
metadata:
  name: nginx-readonlyrootfilesystem-disallowed
  namespace: default
  labels:
    app: nginx-readonlyrootfilesystem
spec:
  ephemeralContainers:
  - name: nginx
    image: nginx
    securityContext:
      readOnlyRootFilesystem: false
